# Generated by Django 5.0.6 on 2024-07-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0002_delete_event_alter_date_product_delete_position3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(choices=[('21.1', ' Akupunktur/ Akupunkt-Meridiantherapie verschiedener Segmente oder Areale'), ('21.2', 'Elektroakupunktur / Elektrotherapie')], max_length=250)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=20)),
                ('count', models.IntegerField(default=1)),
                ('endprice', models.CharField(max_length=255)),
                ('factor', models.IntegerField(blank=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.date')),
            ],
        ),
    ]
