# Generated by Django 5.0.6 on 2024-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0003_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='number',
            field=models.CharField(choices=[('21.1', '21.1'), ('21.2', '21.1')], max_length=250),
        ),
    ]
