# Generated by Django 5.0.6 on 2024-07-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0004_alter_position_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='position',
            name='number',
            field=models.CharField(max_length=250),
        ),
    ]
