# Generated by Django 5.0.6 on 2024-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0005_alter_position_factor_alter_position_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='factor',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
    ]
