# Generated by Django 5.0.6 on 2024-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0007_position_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='invoice',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
