# Generated by Django 5.0.6 on 2024-07-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0010_invoice_show_diagnose'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='already_paid',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('offen', 'offen'), ('bezahlt', 'bezahlt'), ('storniert', 'storniert')], max_length=100),
        ),
    ]
