# Generated by Django 5.0.6 on 2024-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0011_invoice_already_paid_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='diagnose',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
