# Generated by Django 5.0.6 on 2024-07-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0013_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('offen', 'offen'), ('bezahlt', 'bezahlt'), ('storniert', 'storniert'), ('fällig', 'fällig')], default='offen', max_length=100),
        ),
    ]
