# Generated by Django 5.0.6 on 2024-07-08 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0015_alter_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=20)),
                ('count', models.IntegerField(default=1)),
                ('factor', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.date')),
            ],
        ),
    ]
