# Generated by Django 5.0.6 on 2024-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0017_alter_positiondefinition_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiondefinition',
            name='description',
            field=models.CharField(blank='True', max_length=255),
        ),
    ]
