# Generated by Django 5.0.6 on 2024-07-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0018_alter_positiondefinition_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('description', models.CharField(blank='True', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.productdefinition')),
            ],
        ),
    ]
