# Generated by Django 5.0.6 on 2024-07-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0019_productdefinition_anamnese'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdefinition',
            name='category',
            field=models.CharField(default='Bioresonanz', max_length=250),
            preserve_default=False,
        ),
    ]
