# Generated by Django 5.0.6 on 2024-07-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0020_productdefinition_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
