# Generated by Django 5.0.6 on 2024-07-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0021_alter_anamnese_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='text',
            field=models.TextField(),
        ),
    ]
